repos:
  - repo: local
    hooks:
      - id: validate-cruft-up-to-date
        name: Validate Cruft up-to-date
        entry: cruft check
        language: system
        pass_filenames: false
      - id: validate-cruft-no-diff
        name: Validate Cruft drift
        entry: cruft diff --exit-code
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]
        name: Don't commit to main branch
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-symlinks
        name: Check for broken symlinks
      - id: check-json
        name: Check for valid JSON
      - id: check-toml
        name: Check for valid TOML
      - id: check-yaml
        name: Check for valid YAML
      - id: detect-private-key
        name: Check for private keys
      - id: trailing-whitespace
        name: Fix trailing whitespaces
      - id: end-of-file-fixer
        name: Fix missing end-of-file line returns
        exclude: repository.yaml|tests/unit/test-data/
  - repo: https://github.com/hmrc/security-git-hooks
    rev: release/1.9.0
    hooks:
      - id: secrets_filecontent
        name: Checking staged files for sensitive content
        exclude: ".tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$|.xls$|
                    |.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$|.gif$|.bmp$|.webp$|.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$"
      - id: secrets_filename
        name: Checking staged files for sensitive file types
        exclude: ".tar$|.gz$|.jar$|.7z$|.rar$|.bz2$|.zip$|.gzip$|.war$|.ear$|.xlsx$|.xls$|
                    |.docx$|.doc$|.pptx$|.pdf$|.jpg$|.png$|.jpeg$|.tif$|.tiff$|.gif$|.bmp$|.webp$|.svg$|.ico$|.psd$|.exe$|.dll$|.dmg$|.de$|.rpm$"
